######################################################################
# Automatically generated by qmake (2.01a) qui ago 4 10:40:17 2011
######################################################################

QT += network webkit
TEMPLATE = app
TARGET = echotest
DEPENDPATH += .
INCLUDEPATH += .

RESOURCES += resources.qrc

# Input
HEADERS += qwebsocket.h
SOURCES += echotest.cpp qwebsocket.cpp
FORMS += echotest.ui
